image: node:lts-alpine

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  before_script:
    - npm config set "//npm.hodoo.ai/:_authToken" ${NPM_TOKEN}
    - yarn config set registry "https://npm.hodoo.ai"
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn run build

Coverage:
  stage: test
  dependencies:
    - Build
  script:
    - rm -rf coverage
    - yarn coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage

pages:
  stage: deploy
  dependencies:
    - Coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
  only:
    - master

